### ISSUE TITLE
enum doesn't work when in external referenced schema

### ISSUE THREAD

**Issue by chrahunt** [epoberezkin/ajv-pack#8]
Example:

```js
const Ajv = require('Ajv');
const pack = require('ajv-pack');
const requireFromString = require('require-from-string');

let dep = {
  "$schema": "http://json-schema.org/draft-04/schema#",
  "foo": {
    "type": "integer",
    "enum": [1, 2]
  }
};

let moduleCode;
let ajv = new Ajv({ sourceCode: true });
ajv.addSchema(dep, 'definitions.json');
// No ref - all good
let validate = ajv.compile({
  "$schema": "http://json-schema.org/draft-04/schema#",
  "type": "integer",
  "enum": [1, 2]
});
console.log(`Valid: ${validate(1)}`);                // => true
console.log(`Invalid: ${validate(0)}`);              // => false
moduleCode = pack(ajv, validate);
let packedValidate = requireFromString(moduleCode);
console.log(`Valid packed: ${packedValidate(1)}`);   // => true
console.log(`Invalid packed: ${packedValidate(0)}`); // => false

// With ref - some bad
let validate_ref = ajv.compile({
  "$schema": "http://json-schema.org/draft-04/schema#",
  "$ref": "definitions.json#/foo"
});

console.log(`Valid ref: ${validate_ref(1)}`);              // => true
console.log(`Invalid ref: ${validate_ref(0)}`);            // => false
moduleCode = pack(ajv, validate_ref);
let packedValidate_ref = requireFromString(moduleCode);
console.log(`Valid ref packed: ${packedValidate_ref(1)}`); // => error
console.log(`Invalid ref packed: ${packedValidate_ref(0)}`);
```

The error I receive:
```
PS C:\ajv-minimal-example> node index
Valid: true
Invalid: false
Valid ref: true
Invalid ref: false
Valid packed: true
Invalid packed: false
:12
    var schema1 = refVal1.enum;
                  ^

ReferenceError: refVal1 is not defined
    at validate (<anonymous>:12:19)
    at Object.<anonymous> (C:\ajv-minimal-example\index.js:42:34)
    at Module._compile (module.js:541:32)
    at Object.Module._extensions..js (module.js:550:10)
    at Module.load (module.js:458:32)
    at tryModuleLoad (module.js:417:12)
    at Function.Module._load (module.js:409:3)
    at Function.Module.runMain (module.js:575:10)
    at startup (node.js:160:18)
    at node.js:456:3
```
After some testing, things that aren't issues:
1. Refs without `enum`, e.g. just `"type": "integer"`
2. (as seen above) the `validate` function for an `enum`-containing-ref prior to being `pack`ed
3. (as seen above) the packed `validate` function for an `enum`-containing schema

For reference here are my dependencies when running the above example:
```
    "ajv": "^4.9.2",
    "ajv-pack": "^0.2.7",
    "require-from-string": "^1.2.1"
```
And I'm using node v6.2.1.

**Comment by downace** [comment]
I got exactly the same error. Using ajv-pack v0.3.0, ajv v5.2.3

**Comment by timstott** [comment]
Greetings 👋. I have been facing the same issue. I think this fails because we haven't specified the `inlineRefs: false` option to Ajv, an option I found in [this](https://github.com/redbadger/ajv-pack/blob/0.3.0/spec/pack_validate.spec.js#L54-L60) test.

The example above is a little outdated so I will provide a new one to demonstrate that it works.

0. Checkout this repository at `0.3.0`
0. Run `yarn install`
0. Create an *example.js* file at the repository root with the content below.
0. Run `node example.js`

```js
// example.js
const Ajv = require('Ajv');
const pack = require('./index');
const requireFromString = require('require-from-string');

const addressSchema = {
  "$schema": "http://json-schema.org/draft-06/schema#",
  "$id": "schemas/address.json",
  "type": "object",
  "properties": {
    "city": { "type": "string", "enum": ["A", "B"] }
  }
};

const userSchema = {
  "$schema": "http://json-schema.org/draft-06/schema#",
  "$id": "schemas/user.json",
  "type": "object",
  "properties": {
    "id": { "type": "string" },
    "address": { "$ref": "address.json" }
  },
  "additionalProperties": false,
  "required": [
    "id",
    "address"
  ]
};

const ajv = new Ajv({ sourceCode: true, inlineRefs: false });
ajv.addSchema(addressSchema);
const validate = ajv.compile(userSchema);

const user = {
  id: "CU1",
  address: {
    city: "A",
  }
};

validate(user); // OK

const moduleCode = pack(ajv, validate);
const packedValidate = requireFromString(moduleCode);
packedValidate(user); // OK

```

**Comment by epoberezkin** [comment]
you can specify this option I think - --inline-refs.
Can't you?

**Comment by timstott** [comment]
@epoberezkin I stand corrected 🎩 . That works perfectly well.

Is it perhaps still worth leaving this issue open (or creating another) since I believe packing a schema with `inlineRef: true` should still be a viable option?

**Comment by epoberezkin** [comment]
correct

**Comment by haines** [comment]
@epoberezkin I've had a look at this with @timstott and the root cause is the same as #12, so using that branch solves this issue as well. Could you please have a look at that PR?

**Comment by epoberezkin** [comment]
@haines could you maybe make a [failing] PR with a test case for this issue? I will look again at #12, I had some concerns about it.

**Comment by haines** [comment]
@epoberezkin #15 adds a failing test case for this issue. I've cherry-picked that onto #12, and the test passes.
